import { Component, Ingredient, MealTemplate, Technique } from './types';
export const ingredients:Ingredient[]=[
{id:'chicken_breast',name:'Chicken Breast',category:'protein',nutrition:{calories:165,protein:31,fat:3.5,carbs:0,fiber:0,sodium:74},micronutrients:['iron','potassium','niacin'],cost:4.99,unit:'lb',packageSizes:[2,5],shelfLifeRaw:2,shelfLifeCooked:4,freezes:true,diets:['halal','kosher','gluten_free','dairy_free','nut_free'],storage:'refrigerated',aisle:'meat',pantry:false,spice:false,image:'/images/chicken_breast.jpg'},
{id:'brown_rice',name:'Brown Rice',category:'grain',nutrition:{calories:216,protein:5,fat:1.8,carbs:45,fiber:3.5,sodium:10},micronutrients:['magnesium','selenium'],cost:3.25,unit:'lb',packageSizes:[2],shelfLifeRaw:365,shelfLifeCooked:5,freezes:true,diets:['vegetarian','vegan','halal','kosher','gluten_free','dairy_free','nut_free'],storage:'pantry',aisle:'grains',pantry:false,spice:false},
{id:'broccoli',name:'Broccoli',category:'vegetable',nutrition:{calories:55,protein:3.7,fat:.6,carbs:11,fiber:5,sodium:64},micronutrients:['vitamin c','vitamin k'],cost:2.25,unit:'head',packageSizes:[1],shelfLifeRaw:5,shelfLifeCooked:4,freezes:true,diets:['vegetarian','vegan','halal','kosher','gluten_free','dairy_free','nut_free'],storage:'refrigerated',aisle:'produce',pantry:false,spice:false},
{id:'tortilla',name:'Flour Tortillas',category:'bread',nutrition:{calories:140,protein:4,fat:3,carbs:24,fiber:1,sodium:350},micronutrients:['iron'],cost:2.99,unit:'pack',packageSizes:[8],shelfLifeRaw:10,shelfLifeCooked:10,freezes:true,diets:['vegetarian','halal','kosher','dairy_free','nut_free'],storage:'pantry',aisle:'bakery',pantry:false,spice:false},
{id:'lettuce',name:'Romaine Lettuce',category:'vegetable',nutrition:{calories:15,protein:1,fat:0,carbs:3,fiber:2,sodium:8},micronutrients:['vitamin a','folate'],cost:3.49,unit:'head',packageSizes:[1],shelfLifeRaw:6,shelfLifeCooked:1,freezes:false,diets:['vegetarian','vegan','halal','kosher','gluten_free','dairy_free','nut_free'],storage:'refrigerated',aisle:'produce',pantry:false,spice:false},
{id:'oats',name:'Rolled Oats',category:'grain',nutrition:{calories:150,protein:5,fat:3,carbs:27,fiber:4,sodium:0},micronutrients:['iron','magnesium'],cost:4.29,unit:'lb',packageSizes:[2],shelfLifeRaw:365,shelfLifeCooked:5,freezes:false,diets:['vegetarian','vegan','halal','kosher','dairy_free','nut_free'],storage:'pantry',aisle:'breakfast',pantry:false,spice:false},
{id:'greek_yogurt',name:'Greek Yogurt',category:'dairy',nutrition:{calories:100,protein:17,fat:0,carbs:6,fiber:0,sodium:60},micronutrients:['calcium'],cost:5.99,unit:'tub',packageSizes:[5],shelfLifeRaw:10,shelfLifeCooked:10,freezes:false,diets:['vegetarian','halal','kosher','gluten_free','nut_free'],storage:'refrigerated',aisle:'dairy',pantry:false,spice:false},
{id:'teriyaki_sauce',name:'Teriyaki Sauce',category:'sauce',nutrition:{calories:35,protein:1,fat:0,carbs:8,fiber:0,sodium:610},micronutrients:[],cost:3.79,unit:'bottle',packageSizes:[10],shelfLifeRaw:90,shelfLifeCooked:90,freezes:false,diets:['vegetarian','vegan','dairy_free','nut_free'],storage:'refrigerated',aisle:'international',pantry:false,spice:false},
{id:'buffalo_sauce',name:'Buffalo Sauce',category:'sauce',nutrition:{calories:15,protein:0,fat:1,carbs:1,fiber:0,sodium:460},micronutrients:[],cost:3.49,unit:'bottle',packageSizes:[10],shelfLifeRaw:120,shelfLifeCooked:120,freezes:false,diets:['vegetarian','vegan','halal','kosher','gluten_free','dairy_free','nut_free'],storage:'refrigerated',aisle:'condiments',pantry:false,spice:false},
{id:'olive_oil',name:'Olive Oil',category:'pantry',nutrition:{calories:119,protein:0,fat:14,carbs:0,fiber:0,sodium:0},micronutrients:['vitamin e'],cost:8.99,unit:'bottle',packageSizes:[50],shelfLifeRaw:365,shelfLifeCooked:365,freezes:false,diets:['vegetarian','vegan','halal','kosher','gluten_free','dairy_free','nut_free'],storage:'pantry',aisle:'oils',pantry:true,spice:false},
{id:'salt',name:'Salt',category:'spice',nutrition:{calories:0,protein:0,fat:0,carbs:0,fiber:0,sodium:2325},micronutrients:[],cost:1.49,unit:'box',packageSizes:[100],shelfLifeRaw:999,shelfLifeCooked:999,freezes:false,diets:['vegetarian','vegan','halal','kosher','gluten_free','dairy_free','nut_free'],storage:'pantry',aisle:'spices',pantry:true,spice:true}
];
export const techniques:Technique[]=[
{id:'roast_chicken',name:'Roasted Chicken',appliance:'Oven',prepMinutes:10,cookMinutes:30,outputComponentId:'cooked_chicken',yieldServings:6,storageLifeDays:4,inputs:[{ingredientId:'chicken_breast',amount:2,unit:'lb'},{ingredientId:'olive_oil',amount:2,unit:'tbsp'},{ingredientId:'salt',amount:1,unit:'tsp'}],instructions:['Season chicken with olive oil, salt, and pepper.','Roast at 400°F until cooked through.','Rest, slice, and refrigerate in an airtight container.']},
{id:'rice_cooker_rice',name:'Rice Cooker Brown Rice',appliance:'Rice Cooker',prepMinutes:5,cookMinutes:40,outputComponentId:'cooked_rice',yieldServings:8,storageLifeDays:5,inputs:[{ingredientId:'brown_rice',amount:1,unit:'lb'}],instructions:['Rinse rice until water runs mostly clear.','Cook with water in the rice cooker.','Cool quickly and store.']},
{id:'roasted_broccoli',name:'Roasted Broccoli',appliance:'Oven',prepMinutes:10,cookMinutes:20,outputComponentId:'roasted_broccoli',yieldServings:4,storageLifeDays:4,inputs:[{ingredientId:'broccoli',amount:2,unit:'head'},{ingredientId:'olive_oil',amount:1,unit:'tbsp'}],instructions:['Cut broccoli into florets.','Roast on a sheet pan at 425°F.','Store separately to preserve texture.']}
];
export const components:Component[]=[
{id:'cooked_chicken',name:'Cooked Chicken',techniqueId:'roast_chicken',ingredientIds:['chicken_breast'],storageLifeDays:4,servingSize:'4 oz',diets:['halal','kosher','gluten_free','dairy_free','nut_free']},
{id:'cooked_rice',name:'Cooked Brown Rice',techniqueId:'rice_cooker_rice',ingredientIds:['brown_rice'],storageLifeDays:5,servingSize:'3/4 cup',diets:['vegetarian','vegan','halal','kosher','gluten_free','dairy_free','nut_free']},
{id:'roasted_broccoli',name:'Roasted Broccoli',techniqueId:'roasted_broccoli',ingredientIds:['broccoli'],storageLifeDays:4,servingSize:'1 cup',diets:['vegetarian','vegan','halal','kosher','gluten_free','dairy_free','nut_free']},
{id:'teriyaki',name:'Teriyaki Sauce',ingredientIds:['teriyaki_sauce'],storageLifeDays:90,servingSize:'2 tbsp',diets:['vegetarian','vegan','dairy_free','nut_free']},
{id:'buffalo',name:'Buffalo Sauce',ingredientIds:['buffalo_sauce'],storageLifeDays:120,servingSize:'2 tbsp',diets:['vegetarian','vegan','halal','kosher','gluten_free','dairy_free','nut_free']},
{id:'tortilla',name:'Flour Tortilla',ingredientIds:['tortilla'],storageLifeDays:10,servingSize:'1 tortilla',diets:['vegetarian','halal','kosher','dairy_free','nut_free']},
{id:'lettuce',name:'Romaine Lettuce',ingredientIds:['lettuce'],storageLifeDays:6,servingSize:'2 cups',diets:['vegetarian','vegan','halal','kosher','gluten_free','dairy_free','nut_free']},
{id:'oats',name:'Overnight Oats',ingredientIds:['oats','greek_yogurt'],storageLifeDays:4,servingSize:'1 jar',diets:['vegetarian','halal','kosher','nut_free']}
];
export const mealTemplates:MealTemplate[]=[
{id:'chicken_rice_bowl',name:'Teriyaki Chicken Rice Bowl',slots:['lunch','dinner'],cuisine:'Asian-inspired',components:['cooked_chicken','cooked_rice','roasted_broccoli','teriyaki'],diets:['halal','nut_free'],calories:560,protein:43},
{id:'buffalo_wrap',name:'Buffalo Chicken Wrap',slots:['lunch','dinner'],cuisine:'American',components:['cooked_chicken','tortilla','lettuce','buffalo'],diets:['halal','dairy_free','nut_free'],calories:470,protein:36},
{id:'chicken_salad',name:'Chicken Romaine Salad',slots:['lunch','dinner'],cuisine:'American',components:['cooked_chicken','lettuce','buffalo'],diets:['halal','kosher','gluten_free','dairy_free','nut_free'],calories:330,protein:34},
{id:'overnight_oats',name:'Overnight Oats',slots:['breakfast'],cuisine:'Breakfast',components:['oats'],diets:['vegetarian','halal','kosher','nut_free'],calories:310,protein:22}
];
