import { components, ingredients, mealTemplates, techniques } from './data';
import { days, slots } from './defaultPreferences';
import { Component, GroceryItem, MealPlan, MealTemplate, Technique, UserPreferences } from './types';
const byId=<T extends {id:string}>(items:T[])=>Object.fromEntries(items.map(i=>[i.id,i])) as Record<string,T>;
const ingredientById=byId(ingredients), componentById=byId(components), techniqueByOutput=Object.fromEntries(techniques.map(t=>[t.outputComponentId,t])) as Record<string,Technique>;
function activeDiets(prefs:UserPreferences){ return prefs.diets.filter(d=>d!=='none'); }
function allowedMeal(meal:MealTemplate,prefs:UserPreferences){ const restrictions=activeDiets(prefs); if(restrictions.some(d=>!meal.diets.includes(d))) return false; const text=meal.name.toLowerCase(); if(prefs.foodsToAvoid.some(f=>f&&text.includes(f.toLowerCase()))) return false; return meal.components.every(id=>{ const c=componentById[id]; if(!c) return false; if(restrictions.some(d=>!c.diets.includes(d))) return false; const tech=c.techniqueId?techniqueByOutput[c.id]:undefined; return !tech || prefs.appliances.includes(tech.appliance); }); }
function componentIngredients(component:Component){ return component.ingredientIds.map(id=>ingredientById[id]).filter(Boolean); }
export function optimizeMealPlan(prefs:UserPreferences):MealPlan{
 const meals=[] as MealPlan['meals']; const usage=new Map<string,number>(); let rotation=0;
 for(const day of days) for(const slot of slots){ if(!prefs.selectedMeals[day][slot]) continue; const options=mealTemplates.filter(m=>m.slots.includes(slot)&&allowedMeal(m,prefs)); const preferred=options.filter(o=>!prefs.preferredCuisines.length||prefs.preferredCuisines.includes(o.cuisine)); const pool=preferred.length?preferred:options; const meal=pool[rotation%Math.max(pool.length,1)] || mealTemplates[0]; rotation++; meals.push({day,slot,meal}); meal.components.forEach(id=>usage.set(id,(usage.get(id)||0)+1)); }
 const neededIngredients=new Map<string,number>(); const neededTechniques=new Map<string,Technique>(); usage.forEach((count,componentId)=>{ const c=componentById[componentId]; if(!c)return; const tech=c.techniqueId?techniqueByOutput[c.id]:undefined; if(tech){ neededTechniques.set(tech.id,tech); const batches=Math.ceil(count/tech.yieldServings); tech.inputs.forEach(input=>neededIngredients.set(input.ingredientId,(neededIngredients.get(input.ingredientId)||0)+input.amount*batches)); } else componentIngredients(c).forEach(i=>neededIngredients.set(i.id,(neededIngredients.get(i.id)||0)+count)); });
 const groceryList:GroceryItem[]=[]; neededIngredients.forEach((needed,id)=>{ const ingredient=ingredientById[id]; if(!ingredient||ingredient.pantry) return; const packageSize=ingredient.packageSizes.slice().sort((a,b)=>a-b).find(size=>size>=needed) || ingredient.packageSizes[ingredient.packageSizes.length-1]; const packages=Math.ceil(needed/packageSize); groceryList.push({ingredient,packageSize,packages,needed,waste:packages*packageSize-needed,totalCost:packages*ingredient.cost}); });
 const windows=days.flatMap(day=>(['morning','evening'] as const).filter(w=>prefs.cookingWindows[day][w]).map(window=>({day,window}))); const cookingSchedule:MealPlan['cookingSchedule']=[]; const techs=[...neededTechniques.values()]; let cursor=0; for(const tech of techs){ const win=windows[cursor%Math.max(windows.length,1)]||{day:'Sunday' as const,window:'evening' as const}; const totalMinutes=tech.prepMinutes+tech.cookMinutes; const labels=meals.filter(m=>m.meal.components.includes(tech.outputComponentId)).map(m=>`${m.day} ${m.slot}`); const last=cookingSchedule.at(-1); if(last&&last.day===win.day&&last.window===win.window&&last.totalMinutes+totalMinutes<=prefs.maxSessionMinutes){ last.techniques.push(tech); last.totalMinutes+=totalMinutes; last.mealsUsedBy.push(...labels);} else cookingSchedule.push({day:win.day,window:win.window,techniques:[tech],mealsUsedBy:labels,totalMinutes}); cursor++; }
 const totalCost=groceryList.reduce((s,i)=>s+i.totalCost,0); const totalWaste=groceryList.reduce((s,i)=>s+i.waste,0); return {meals,groceryList,cookingSchedule,totalCost,costPerMeal:meals.length?totalCost/meals.length:0,wasteScore:totalWaste};
}
